{{- if .Values.route.create }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.model.name }}
  labels:
    {{- include "llama-guard.labels" . | nindent 4 }}
    app: {{ .Values.model.name }}
spec:
  path: /
  to:
    kind: Service
    name: {{ .Values.model.name }}-predictor
    weight: 100
  port:
    targetPort: http
  {{- with .Values.route.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  wildcardPolicy: None
{{- end }}
