kind: Deployment
apiVersion: apps/v1
metadata:
  name: ocp-mcp-server
  labels:
    {{- include "openshift-mcp.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "openshift-mcp.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "openshift-mcp.selectorLabels" . | nindent 8 }}
        deployment: ocp-mcp-server
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: ocp-mcp-server
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: {{ .Values.service.port }}
            protocol: TCP
        command: ["./kubernetes-mcp-server"]
        args: ["--sse-port", "{{ .Values.ssePort }}"]
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
