apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-mcp-server
  labels:
    {{- include "slack-mcp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "slack-mcp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "slack-mcp.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: slack-mcp-server
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/sh", "-c"]
        args:
        - |
          npx -y supergateway --stdio "node dist/index.js" --port {{ .Values.service.targetPort }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        env:
        - name: NPM_CONFIG_CACHE
          value: /tmp/.npm
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "slack-mcp.secretName" . }}
              key: slack-bot-token
        - name: SLACK_TEAM_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "slack-mcp.secretName" . }}
              key: slack-team-id
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
