apiVersion: llamastack.io/v1alpha1
kind: LlamaStackDistribution
metadata:
  name: llamastack
spec:
  replicas: 1
  server:
    containerSpec:
      env:
        - name: OTEL_SERVICE_NAME
          value: llamastack
      name: llama-stack
      port: 8321
    distribution:
      name: rh-dev
    userConfig:
      configMapName: llama-stack-config
