# Slack MCP Server Configuration

image:
  repository: quay.io/redhat-et/slack-mcp-server
  tag: latest
  pullPolicy: Always

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

# Slack credentials - configure via secret
slack:
  # Option 1: Use existing secret
  existingSecret: ""
  # Option 2: Create secret with provided values (not recommended for production)
  botToken: "xoxb-"
  teamId: "T..."

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

nodeSelector: {}

tolerations: []

affinity: {}
